
# Examples for "p2c", the Pascal to C translator.


# The following definitions assume p2c has been installed as suggested in 
# distrib\readme.os2.
CC  = gcc
P2C = p2c
INC = c:\emx\p2c 
LIB = c:\emx\lib\libp2c.a


default: comp


# Translating everything:

trans:  fact.c  e.c  self.c  cref.c  basic.c

fact.c: fact.p
	$(P2C) fact.p

e.c: e.p
	$(P2C) e.p

self.c: self.p
	$(P2C) self.p

cref.c: cref.p
	$(P2C) cref.p

basic.c: basic.p
	$(P2C) basic.p



# Compiling everything:

comp:  fact  exp  self  cref  basic

fact: fact.c
	$(CC) -I$(INC) fact.c $(LIB) -o fact.exe

exp: e.c
	$(CC) -I$(INC) e.c $(LIB) -o e.exe

self: self.c
	$(CC) -I$(INC) self.c $(LIB) -o self.exe

cref: cref.c
	$(CC) -I$(INC) cref.c $(LIB) -o cref.exe

basic: basic.c
	$(CC) -I$(INC) basic.c $(LIB) -o basic.exe
